#!/usr/bin/env python3
# tools/amalgamate.py
#
# Glue the multi-file dans-util sources (plus its vendored dans-core headers)
# into one single-header file, stb-style: declarations are always compiled,
# the out-of-line function bodies sit behind DANS_UTIL_IMPLEMENTATION.
#
# Run from anywhere:  python tools/amalgamate.py

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
INC = REPO / "include" / "dans"
SRC = REPO / "src"
CORE = REPO / "vendor" / "dans-core" / "include" / "dans"
OUT = REPO / "single_include" / "dans" / "dans_util.hpp"

GUARD = "DANS_UTIL_AMALGAMATED_HPP"
IMPL_FLAG = "DANS_UTIL_IMPLEMENTATION"
IMPL_DONE = "DANS_UTIL_IMPLEMENTATION_DONE"

# Embedded first so the type aliases and the def/cpy markers exist before any
# header that uses them. Keep the original include-guard names: a real
# dans-core in the same TU then mutually-excludes with this copy.
CORE_HEADERS = ["types.hpp", "development_markers.hpp"]

# Declaration half. Only internal edge is chrono -> dev (DANS_PANIC), so dev
# must appear before chrono; everything else only leans on the core above.
DECL_HEADERS = [
    "overload.hpp",
    "lit.hpp",
    "math.hpp",
    "stats.hpp",
    "views.hpp",
    "dev.hpp",
    "str.hpp",
    "fmt.hpp",
    "env.hpp",
    "random.hpp",
    "chrono.hpp",
    "util.hpp",
]

# Implementation half. Every body is forward-declared above, so order is free.
IMPL_SOURCES = [
    "dev.cpp",
    "str.cpp",
    "fmt.cpp",
    "env.cpp",
    "random.cpp",
    "chrono.cpp",
    "util.cpp",
]

DANS_INCLUDE = re.compile(r'^\s*#\s*include\s*[<"]dans/')
PRAGMA_ONCE = re.compile(r"^\s*#\s*pragma\s+once\b")
PATH_COMMENT = re.compile(r"^//\s*(?:include|src|app)/")
URL_COMMENT = re.compile(r"^//\s*https?://")
SCAFFOLD = {"//", "// Externals", "// StdLib", "// Internals", "// External"}


def clean(path: Path) -> list[str]:
    """Drop the dans-internal includes, the pragma-once lines, and the per-file
    comment scaffolding. Keep the include guard, the std includes (inline, so
    the conditional <stdfloat> stays wrapped in its #if), and the content."""
    out: list[str] = []
    for ln in path.read_text(encoding="utf-8").splitlines():
        s = ln.strip()
        if DANS_INCLUDE.match(ln):
            continue
        if PRAGMA_ONCE.match(ln):
            continue
        if s in SCAFFOLD:
            continue
        if PATH_COMMENT.match(s) or URL_COMMENT.match(s):
            continue
        out.append(ln.rstrip())

    collapsed: list[str] = []
    for ln in out:
        if ln == "" and collapsed and collapsed[-1] == "":
            continue
        collapsed.append(ln)
    while collapsed and collapsed[0] == "":
        collapsed.pop(0)
    while collapsed and collapsed[-1] == "":
        collapsed.pop()
    return collapsed


def banner(title: str) -> list[str]:
    bar = "// " + "=" * 74
    return [bar, f"// {title}", bar]


def read_version() -> str:
    text = (INC / "util.hpp").read_text(encoding="utf-8")
    m = re.search(r'version\s*=\s*"([^"]+)"', text)
    if not m:
        raise SystemExit("could not find version string in include/dans/util.hpp")
    return m.group(1)


def main() -> None:
    version = read_version()
    out: list[str] = []

    out += [
        "// dans-util - single-header amalgamation",
        f"// version {version}",
        "//",
        "// Generated by tools/amalgamate.py from the dans-util sources.",
        "// Do not edit this file by hand; edit the sources under include/ and src/",
        "// then regenerate with:  python tools/amalgamate.py",
        "//",
        "// In exactly one translation unit, define the implementation macro before",
        "// including this header to compile the out-of-line function bodies:",
        "//",
        f"//     #define {IMPL_FLAG}",
        "//     #include <dans/dans_util.hpp>",
        "",
        f"#ifndef {GUARD}",
        f"#define {GUARD}",
        "",
        f'#define DANS_UTIL_VERSION "{version}"',
        "",
    ]

    for h in CORE_HEADERS:
        out += banner(f"vendored core: dans/{h}")
        out += clean(CORE / h)
        out.append("")

    for h in DECL_HEADERS:
        out += banner(f"include/dans/{h}")
        out += clean(INC / h)
        out.append("")

    out += [f"#endif  // {GUARD}", ""]

    out += [
        f"#ifdef {IMPL_FLAG}",
        f"#ifndef {IMPL_DONE}",
        f"#define {IMPL_DONE}",
        "",
    ]
    for s in IMPL_SOURCES:
        out += banner(f"src/{s}")
        out += clean(SRC / s)
        out.append("")
    out += [f"#endif  // {IMPL_DONE}", f"#endif  // {IMPL_FLAG}", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}  (version {version}, {len(out)} lines)")


if __name__ == "__main__":
    main()
